<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saj" ignored="0" name="LoginTest" tests="3" failures="1" timestamp="09 Feb 2019 17:35:10 GMT" time="22.971" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="8.824" classname="tests.LoginTests"/>
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="4.174" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="4.804" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]">
      <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
at pages.BasePage.assertEquals(BasePage.java:45)
at pages.LoginPage.verifyLoginPassword(LoginPage.java:42)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:57)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- LoginTest -->
